### ISSUE TITLE
I don't see the code for ContactOwnerMixin

### ISSUE THREAD

**Issue by cnk** [nyergler/effective-django#17]
Your Contact permission example looks like exactly what I need in order to do instance level permission checking for a model. From the text, it sounds like the information I need is in ContactOwnerMixin - but I don't see the code for that class. Is that available somewhere?

**Comment by nyergler** [comment]
It looks like it was omitted from the source file when I pushed. (It's possible I didn't get it totally written, since it's not in the demo source repo, either.) The necessary code is included in the `ContactView` implementation at the bottom of http://effectivedjango.com/tutorial/authzn.html; specifically the `get_object` method, which Django uses to get the object the class based view applies to.

I have a few pending edits to that page, and I'll try to get this change wrapped in with those. Leaving the issue open as a reminder.

**Comment by nyergler** [comment]
This has been updated on the site:

http://www.effectivedjango.com/tutorial/authzn.html#checking-ownership

Thanks again for pointing this out!
