### ISSUE TITLE
PDF version generation problem

### ISSUE THREAD

**Issue by Mte90** [nyergler/effective-django#20]
I've followed the guides but i get an error for the file blockdiag (removed the line in views.rst to fix) but the pdf generated have only 41 page repsect to epub version downloadable from the site that have 140+ pages.

**Comment by nyergler** [comment]
What error did you get when you tried to build the PDF? 

The PDF only includes the tutorial, while the epub contains all the other notes, as well. This is because the PDF is used as a handout when I've presented the tutorial at conferences.

**Comment by Mte90** [comment]
The pdf stop to 41 page about Authorization.
Now i don't get errors but i can see that in EffectiveDjango.tex there are the content is the same of the pdf that finish with 8.3 chapter that is this page http://www.effectivedjango.com/tutorial/authzn.html.
Also is appended the text about the license of the ebook.
Maybe there is a bug that concat the latex files in EffectiveDjango.tex?

**Comment by nyergler** [comment]
Authorization is the last section of the tutorial, and since the PDF only includes the tutorial, that's where I'd expect it to end. 

Are you referring to the text "“Effective Django” is licensed under the Creative Commons Attribution-ShareAlike 4.0 International License." being appended? That's normal; you can see at http://www.effectivedjango.com/tutorial/index.html that that text appears below the table of contents. The way Sphinx assembles means that text will appear below the Authzn section.

**Comment by Mte90** [comment]
To get the complete guide, like in epub format, in pdf version there is a way?

**Comment by nyergler** [comment]
You could change the Sphinx configuration (`latex_documents` in `conf.py`) to point to `index` instead of `tutorial/index`. 

This doesn't seem like an actual issue with the project, so I'm going to close.

**Comment by Mte90** [comment]
The error that I get with this edit (the same of yesterday):
```
LaTeX Warning: File `blockdiag-f59ab43c77434baadf97d5c3b6e7930f99ed685d.png' no
t found on input line 3916.


! Package pdftex.def Error: File `blockdiag-f59ab43c77434baadf97d5c3b6e7930f99e
d685d.png' not found.

See the pdftex.def package documentation for explanation.
Type  H <return>  for immediate help.
```

Maybe add this info in the readme will not bad :-)
